/**
 * MikroTik Auto Backup System
 * Schedules and stores device configuration backups
 */

const { v4: uuidv4 } = require('uuid');
const crypto = require('crypto');

const backupStore = {
  schedules: [],
  backups: [],
};

// Seed sample schedules
const seedSchedules = () => {
  if (backupStore.schedules.length > 0) return;
  backupStore.schedules.push(
    {
      id: uuidv4(),
      name: 'Daily Core Router Backup',
      device_type: 'routeros',
      ip_address: '192.168.88.1',
      api_port: 8728,
      username: 'backup_user',
      password_encrypted: crypto.randomBytes(16).toString('hex'),
      schedule: 'daily',
      time: '02:00',
      enabled: true,
      last_run: null,
      last_status: 'never',
      created_at: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      name: 'Weekly Branch Router Backup',
      device_type: 'routeros',
      ip_address: '192.168.88.2',
      api_port: 8728,
      username: 'backup_user',
      password_encrypted: crypto.randomBytes(16).toString('hex'),
      schedule: 'weekly',
      time: '03:00',
      enabled: true,
      last_run: null,
      last_status: 'never',
      created_at: new Date().toISOString(),
    }
  );
};
seedSchedules();

// ─── Create Backup Schedule ───
function createSchedule(data) {
  const schedule = {
    id: uuidv4(),
    name: data.name,
    device_type: data.device_type || 'routeros',
    ip_address: data.ip_address,
    api_port: data.api_port || 8728,
    username: data.username,
    password_encrypted: crypto.randomBytes(16).toString('hex'), // Encrypt in production
    schedule: data.schedule || 'daily',
    time: data.time || '02:00',
    enabled: data.enabled !== false,
    last_run: null,
    last_status: 'never',
    created_at: new Date().toISOString(),
  };
  backupStore.schedules.push(schedule);
  return schedule;
}

// ─── Run Backup ───
async function runBackup(scheduleId) {
  const schedule = backupStore.schedules.find(s => s.id === scheduleId);
  if (!schedule) return { success: false, message: 'Schedule not found' };

  const startTime = new Date().toISOString();

  try {
    // In production, this would connect to the MikroTik API
    // For now, simulate a backup
    const configContent = `# MikroTik Configuration Backup
# Device: ${schedule.ip_address}
# Date: ${startTime}
# Generated by MikroTik Config Builder

# Note: This is a simulated backup. In production, the actual
# /export output from the router would be captured here.

/system identity set name="BackedUpRouter"
`;

    const backup = {
      id: uuidv4(),
      schedule_id: schedule.id,
      device_name: schedule.name,
      ip_address: schedule.ip_address,
      config_content: configContent,
      file_size: Buffer.byteLength(configContent, 'utf8'),
      status: 'success',
      created_at: startTime,
    };

    backupStore.backups.unshift(backup);
    schedule.last_run = startTime;
    schedule.last_status = 'success';

    return { success: true, backup };
  } catch (error) {
    const backup = {
      id: uuidv4(),
      schedule_id: schedule.id,
      device_name: schedule.name,
      ip_address: schedule.ip_address,
      config_content: '',
      file_size: 0,
      status: 'failed',
      error: error.message,
      created_at: startTime,
    };

    backupStore.backups.unshift(backup);
    schedule.last_run = startTime;
    schedule.last_status = 'failed';

    return { success: false, message: error.message };
  }
}

// ─── Run All Enabled Backups ───
async function runAllBackups() {
  const results = { total: 0, success: 0, failed: 0, errors: [] };

  for (const schedule of backupStore.schedules) {
    if (!schedule.enabled) continue;
    results.total++;

    const result = await runBackup(schedule.id);
    if (result.success) {
      results.success++;
    } else {
      results.failed++;
      results.errors.push({ schedule: schedule.name, error: result.message });
    }
  }

  return results;
}

// ─── Get Backups ───
function getBackups(scheduleId, limit = 50) {
  let backups = backupStore.backups;
  if (scheduleId) backups = backups.filter(b => b.schedule_id === scheduleId);
  return backups.slice(0, limit);
}

// ─── Get Schedule ───
function getSchedule(id) {
  return backupStore.schedules.find(s => s.id === id);
}

// ─── Get All Schedules ───
function getAllSchedules() {
  return backupStore.schedules;
}

// ─── Update Schedule ───
function updateSchedule(id, data) {
  const idx = backupStore.schedules.findIndex(s => s.id === id);
  if (idx === -1) return null;
  backupStore.schedules[idx] = { ...backupStore.schedules[idx], ...data };
  return backupStore.schedules[idx];
}

// ─── Delete Schedule ───
function deleteSchedule(id) {
  const idx = backupStore.schedules.findIndex(s => s.id === id);
  if (idx === -1) return null;
  return backupStore.schedules.splice(idx, 1)[0];
}

// ─── Get Backup Content ───
function getBackupContent(backupId) {
  const backup = backupStore.backups.find(b => b.id === backupId);
  if (!backup) return null;
  return {
    id: backup.id,
    device_name: backup.device_name,
    ip_address: backup.ip_address,
    content: backup.config_content,
    created_at: backup.created_at,
  };
}

module.exports = {
  backupStore,
  createSchedule,
  runBackup,
  runAllBackups,
  getBackups,
  getSchedule,
  getAllSchedules,
  updateSchedule,
  deleteSchedule,
  getBackupContent,
};
