/**
 * In-memory storage for Zero-Touch Provisioning
 * Extends the base memory store with routers, provision_logs, provision_events
 */

const { v4: uuidv4 } = require("uuid");
const crypto = require("crypto");

// Self-contained store
const store = {
  routers: [],
  provision_logs: [],
  provision_events: [],
};

function generateToken() {
  return `prov-${crypto.randomBytes(24).toString("hex")}`;
}

function escapeRouterValue(value) {
  if (value === null || value === undefined) return "";
  const str = String(value);
  return str
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "")
    .replace(/\r/g, "")
    .replace(/\t/g, " ");
}

function buildFetchCommand(url, destination, keepResult = true) {
  const safeUrl = escapeRouterValue(url);
  const parts = ["/tool fetch"];

  if (/^https:/i.test(url)) {
    parts.push("mode=https");
    parts.push("check-certificate=no");
  } else {
    parts.push("mode=http");
  }

  parts.push(`url="${safeUrl}"`);

  if (destination) {
    parts.push(`dst-path=${destination}`);
  }

  if (!keepResult) {
    parts.push("keep-result=no");
  }

  return parts.join(" ");
}

function logProvision(store, token, routerId, action, status, details, ip, ua) {
  store.provision_logs.push({
    id: uuidv4(),
    token,
    router_id: routerId || null,
    ip_address: ip || "unknown",
    user_agent: ua || "unknown",
    action,
    status,
    details,
    created_at: new Date().toISOString(),
  });
}

function generateProvisionScript(router, options = {}) {
  const lines = [];
  const wanIface = router.wan_interface || "ether1";
  const lanBridge = router.lan_interface || "bridge1";
  const lanIp = router.lan_ip || "192.168.88.1/24";
  const lanGateway = lanIp.split("/")[0];
  const lanNetwork = lanIp.replace(/\d+\/\d+/, "0/24");
  const dhcpStart = router.dhcp_start || "192.168.88.100";
  const dhcpEnd = router.dhcp_end || "192.168.88.200";

  lines.push("#############################################");
  lines.push("# MikroTik Auto-Provisioning Script");
  lines.push("# Generated by MikroTik Billing System");
  lines.push(`# Router: ${router.name}`);
  lines.push(`# Identity: ${router.identity || router.name}`);
  lines.push(`# Model: ${router.model || "Unknown"}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push("#############################################");
  lines.push("");

  // System Identity
  lines.push("# System Identity");
  lines.push(
    `/system identity set name="${escapeRouterValue(router.identity || router.name)}"`,
  );
  lines.push("/system clock set time-zone-name=Africa/Nairobi");
  lines.push("");

  // DNS Configuration
  lines.push("# DNS Configuration");
  let dnsServers = "8.8.8.8,8.8.4.4,1.1.1.1";
  if (router.dns_servers) {
    if (Array.isArray(router.dns_servers)) {
      const filtered = router.dns_servers.filter(
        (s) => s && typeof s === "string" && s.trim(),
      );
      if (filtered.length > 0) {
        dnsServers = filtered.map((s) => escapeRouterValue(s.trim())).join(",");
      }
    } else if (
      typeof router.dns_servers === "string" &&
      router.dns_servers.trim()
    ) {
      dnsServers = escapeRouterValue(router.dns_servers.trim());
    }
  }
  lines.push(`/ip dns set servers=${dnsServers}`);
  lines.push("/ip dns set allow-remote-requests=yes");
  lines.push("/ip dns set cache-size=10000KiB");
  lines.push("");

  // NTP Configuration
  lines.push("# NTP Configuration");
  lines.push("/system ntp client set enabled=yes");
  let ntpServers = ["pool.ntp.org", "time.google.com"];
  if (router.ntp_servers) {
    if (Array.isArray(router.ntp_servers)) {
      const filtered = router.ntp_servers.filter(
        (s) => s && typeof s === "string" && s.trim(),
      );
      if (filtered.length > 0) {
        ntpServers = filtered;
      }
    } else if (
      typeof router.ntp_servers === "string" &&
      router.ntp_servers.trim()
    ) {
      ntpServers = [router.ntp_servers.trim()];
    }
  }
  if (ntpServers.length > 0) {
    const serversStr = ntpServers
      .filter((s) => s && typeof s === "string" && s.trim())
      .map((s) => escapeRouterValue(s.trim()))
      .join(",");
    lines.push(`/system ntp client set servers="${serversStr}"`);
  }
  lines.push("/system ntp client set mode=unicast");
  lines.push("");

  // Logging
  lines.push("# Logging Configuration");
  lines.push(
    ":do { /system logging set 0 action=memory topics=info } on-error={}",
  );
  lines.push(
    ":do { /system logging set 1 action=memory topics=warning } on-error={}",
  );
  lines.push(
    ":do { /system logging set 2 action=memory topics=error } on-error={}",
  );
  lines.push(
    ":do { /system logging set 3 action=memory topics=critical } on-error={}",
  );
  lines.push(
    ":do { /system logging set 4 action=disk topics=account } on-error={}",
  );
  lines.push(
    ":do { /system logging set 5 action=disk topics=firewall } on-error={}",
  );
  lines.push("");

  // WAN Configuration
  lines.push("# WAN Configuration");
  lines.push(
    `:do { /ip dhcp-client add interface=${wanIface} add-default-route=yes use-peer-dns=no comment="WAN - Auto-configured" } on-error={}`,
  );
  lines.push("");

  // LAN Bridge
  lines.push("# LAN Bridge Configuration");
  lines.push(
    `/interface bridge add name=${lanBridge} protocol=rstp comment="Auto-created LAN bridge"`,
  );
  lines.push("");

  // Add LAN ports to bridge (ether2-ether8 or all ports except WAN)
  lines.push("# Bridge LAN Ports");
  const lanPorts = router.lan_ports || [
    "ether2",
    "ether3",
    "ether4",
    "ether5",
    "ether6",
    "ether7",
    "ether8",
  ];
  lanPorts.forEach((port) => {
    if (port !== wanIface) {
      lines.push(
        `/interface bridge port add bridge=${lanBridge} interface=${port} comment="Auto-bridge ${port}"`,
      );
    }
  });
  lines.push("");

  // LAN IP Address
  lines.push("# LAN IP Address");
  lines.push(
    `/ip address add address=${lanIp} interface=${lanBridge} comment="LAN Gateway"`,
  );
  lines.push("");

  // NAT Masquerade
  lines.push("# NAT Configuration");
  lines.push(
    `/ip firewall nat add chain=srcnat action=masquerade out-interface=${wanIface} comment="Auto-NAT Masquerade"`,
  );
  lines.push("");

  // DHCP Server for LAN
  lines.push("# DHCP Server Configuration");
  lines.push("/ip pool add name=dhcp_pool ranges=" + dhcpStart + "-" + dhcpEnd);
  lines.push(
    `/ip dhcp-server network add address=${lanNetwork} gateway=${lanGateway} dns-server=${lanGateway} domain="local"`,
  );
  lines.push(
    `/ip dhcp-server add name=dhcp_lan interface=${lanBridge} address-pool=dhcp_pool disabled=no lease-time=3d comment="Auto DHCP Server"`,
  );
  lines.push("");

  // Advanced Firewall Rules
  lines.push("# Firewall Filter Rules");
  lines.push("# Input Chain");
  lines.push(
    '/ip firewall filter add chain=input action=accept connection-state=established,related,untracked comment="Allow established connections"',
  );
  lines.push(
    '/ip firewall filter add chain=input action=drop connection-state=invalid comment="Drop invalid connections"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=icmp action=accept comment="Allow ICMP ping"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=udp port=123 action=accept comment="Allow NTP"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=tcp dst-port=22 action=accept comment="Allow SSH"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=tcp dst-port=8291 action=accept comment="Allow WinBox"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=tcp dst-port=8728 action=accept comment="Allow API"',
  );
  lines.push(
    '/ip firewall filter add chain=input protocol=tcp dst-port=443 action=accept comment="Allow HTTPS"',
  );
  lines.push(
    '/ip firewall filter add chain=input action=drop comment="Drop all other input"',
  );
  lines.push("");
  lines.push("# Forward Chain");
  lines.push(
    '/ip firewall filter add chain=forward action=accept connection-state=established,related,untracked comment="Forward established"',
  );
  lines.push(
    '/ip firewall filter add chain=forward action=drop connection-state=invalid comment="Drop invalid forward"',
  );
  lines.push(
    `/ip firewall filter add chain=forward in-interface=${lanBridge} action=accept comment="Allow LAN to WAN"`,
  );
  lines.push(
    '/ip firewall filter add chain=forward action=drop comment="Drop all other forward"',
  );
  lines.push("");

  // FastTrack for performance
  lines.push("# FastTrack Connection Tracking");
  lines.push(
    '/ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related comment="FastTrack established connections"',
  );
  lines.push("");

  // Connection Tracking
  lines.push("# Connection Tracking Settings");
  lines.push(
    "/ip firewall connection tracking set tcp-close-wait-time=10s tcp-time-wait-time=10s",
  );
  lines.push("");

  // RADIUS Configuration
  if (
    router.radius_server &&
    router.radius_secret &&
    router.radius_server.trim() &&
    router.radius_secret.trim()
  ) {
    lines.push("# RADIUS Configuration");
    lines.push(
      `/radius add address="${escapeRouterValue(router.radius_server)}" secret="${escapeRouterValue(router.radius_secret)}" service=ppp,hotspot timeout=3s comment="Auto-provisioned RADIUS"`,
    );
    lines.push("/ppp aaa set use-radius=yes accounting=yes");
    lines.push("/ip hotspot aaa set use-radius=yes accounting=yes");
    lines.push("");
  }

  // PPPoE Server
  if (router.pppoe_enabled) {
    lines.push("# PPPoE Server Configuration");
    const pppoeIface = router.pppoe_interface || "ether2";
    const serviceName = router.pppoe_service_name || "ISP-PPPoE";
    const pppoePool = router.pppoe_pool || "10.10.0.100-10.10.0.200";
    const pppoeGateway = router.pppoe_gateway || "10.10.0.1";
    const rateLimit = router.pppoe_rate_limit || "10M/10M";

    lines.push(
      `/interface pppoe-server server add service-name="${escapeRouterValue(serviceName)}" interface=${pppoeIface} max-mtu=1492 max-mru=1492 authentication=mschap2 disabled=no comment="Auto-provisioned PPPoE"`,
    );
    lines.push("/ip pool add name=pppoe_pool ranges=" + pppoePool);
    lines.push(
      `/ppp profile add name=pppoe_default local-address=${pppoeGateway} remote-address=pppoe_pool rate-limit=${rateLimit} change-tcp-mss=yes comment="Auto PPPoE Profile"`,
    );
    lines.push(
      "/ppp profile set default use-compression=yes use-encryption=yes",
    );
    lines.push("");
  }

  // Hotspot Configuration
  if (router.hotspot_enabled) {
    lines.push("# Hotspot Configuration");
    const hotspotIp = router.hotspot_ip || "192.168.90.1/24";
    const hotspotGateway = hotspotIp.split("/")[0];
    const hotspotNetwork = hotspotIp.replace(/\d+\/\d+/, "0/24");
    const hotspotPool = router.hotspot_pool || "192.168.90.100-192.168.90.200";

    lines.push("/ip pool add name=hs_pool ranges=" + hotspotPool);
    lines.push(
      '/ip hotspot profile add name=hs-prof dns-name="login.local" hotspot-address="' +
        hotspotGateway +
        '" login-by=cookie,http-pap',
    );
    lines.push(
      `/ip hotspot user profile set default idle-timeout=10m keepalive-timeout=2m shared-users=1`,
    );
    lines.push(
      `/ip hotspot add name=hotspot1 interface=${lanBridge} address-pool=hs_pool profile=hs-prof disabled=no`,
    );
    lines.push(
      `/ip address add address=${hotspotIp} interface=${lanBridge} comment="Hotspot Gateway"`,
    );
    lines.push(
      `/ip dhcp-server network add address=${hotspotNetwork} gateway=${hotspotGateway} dns-server=${hotspotGateway}`,
    );
    lines.push("");
  }

  // Bandwidth Control / Simple Queues
  if (router.bandwidth_control) {
    lines.push("# Bandwidth Control");
    lines.push(
      '/queue simple add name=default-limit target=192.168.88.0/24 max-limit=10M/10M comment="Default bandwidth limit"',
    );
    lines.push("");
  }

  // VLAN Support (if configured)
  if (router.vlans && router.vlans.length > 0) {
    lines.push("# VLAN Configuration");
    router.vlans.forEach((vlan) => {
      lines.push(
        `/interface vlan add name=vlan${vlan.id} vlan-id=${vlan.id} interface=${lanBridge} comment="${vlan.name || "VLAN " + vlan.id}"`,
      );
      if (vlan.ip) {
        lines.push(
          `/ip address add address=${vlan.ip} interface=vlan${vlan.id} comment="VLAN ${vlan.id} IP"`,
        );
      }
    });
    lines.push("");
  }

  // Static Routes (if configured)
  if (router.static_routes && router.static_routes.length > 0) {
    lines.push("# Static Routes");
    router.static_routes.forEach((route) => {
      lines.push(
        `/ip route add dst-address=${route.dst} gateway=${route.gateway} comment="${route.comment || "Static route"}"`,
      );
    });
    lines.push("");
  }

  // Security Hardening
  lines.push("# Management Services");
  lines.push(
    "# Review and apply these manually after first successful provisioning if needed.",
  );
  lines.push("/ip service set telnet disabled=yes");
  lines.push("/ip service set ftp disabled=yes");
  lines.push("/ip service set www disabled=yes");
  lines.push("/ip ssh set strong-crypto=yes");
  lines.push(`# Recommended API port: ${router.mgmt_port || 8728}`);
  lines.push("");

  // SNMP (if configured)
  if (router.snmp_enabled) {
    lines.push("# SNMP Configuration");
    lines.push(
      '/snmp set enabled=yes contact="' +
        (router.snmp_contact || "admin@local") +
        '" location="' +
        (router.snmp_location || "Main Office") +
        '"',
    );
    if (router.snmp_community) {
      lines.push(
        `/snmp community set 0 name="${router.snmp_community}" read-access=yes write-access=no`,
      );
    }
    lines.push("");
  }

  // Backup Configuration
  lines.push("# Backup Configuration");
  lines.push("/system backup save name=auto-provision-backup");
  lines.push("");

  // Callback to provisioning server
  lines.push("# Callback to Provisioning Server");
  const callbackBaseUrl =
    options.callbackBaseUrl ||
    router.callback_url ||
    process.env.PUBLIC_APP_URL ||
    "";
  if (callbackBaseUrl) {
    lines.push(
      buildFetchCommand(
        `${callbackBaseUrl.replace(/\/$/, "")}/mikrotik/provision/callback/${router.provision_token}`,
        null,
        false,
      ),
    );
  } else {
    lines.push(
      "# Callback URL not configured. Set PUBLIC_APP_URL or provide a callback base URL from the server.",
    );
  }
  lines.push("");

  // Success Message
  lines.push("# Provisioning Complete");
  lines.push(
    '/log info message="MikroTik Router provisioned successfully by billing system"',
  );
  lines.push("");

  lines.push("#############################################");
  lines.push("# End of Auto-Provisioning Script");
  lines.push(
    "# Review management services and firewall policy before using this on public WAN links",
  );
  lines.push("#############################################");

  return lines.join("\n");
}

module.exports = {
  extendStore: () => store,
  generateToken,
  logProvision,
  generateProvisionScript,
  buildFetchCommand,

  _updateRouterStatus(routerId, status) {
    const router = store.routers.find((r) => r.id === routerId);
    if (router) {
      router.provision_status = status;
      router.last_provisioned_at = new Date().toISOString();
      router.provision_attempts = (router.provision_attempts || 0) + 1;
      router.updated_at = new Date().toISOString();
    }
  },

  _regenerateToken(routerId) {
    const router = store.routers.find((r) => r.id === routerId);
    if (router) {
      router.provision_token = generateToken();
      router.provision_status = "pending";
      router.updated_at = new Date().toISOString();
    }
    return router;
  },

  query: async (text, params) => {
    const lowerText = text.toLowerCase();

    // SELECT routers
    if (lowerText.includes("select") && lowerText.includes("from routers")) {
      if (lowerText.includes("where provision_token")) {
        const router = store.routers.find(
          (r) => r.provision_token === params[0],
        );
        return { rows: router ? [router] : [] };
      }
      if (lowerText.includes("where id")) {
        const router = store.routers.find((r) => r.id === params[0]);
        return { rows: router ? [router] : [] };
      }
      if (lowerText.includes("where project_id")) {
        const routers = store.routers.filter((r) => r.project_id === params[0]);
        return { rows: routers };
      }
      return { rows: store.routers };
    }

    // INSERT routers
    if (lowerText.includes("insert into routers")) {
      const router = {
        id: params[0],
        project_id: params[1],
        name: params[2],
        identity: params[3] || params[2],
        model: params[4] || "",
        mac_address: params[5] || "",
        ip_address: params[6] || "",
        wan_interface: params[7] || "ether1",
        lan_interface: params[8] || "bridge1",
        provision_token: params[9] || generateToken(),
        provision_status: params[10] || "pending",
        last_provisioned_at: null,
        provision_attempts: 0,
        dns_servers: params[11] || ["8.8.8.8", "8.8.4.4"],
        ntp_servers: params[12] || ["pool.ntp.org"],
        radius_server: params[13] || "",
        radius_secret: params[14] || "",
        radius_port: params[15] || 1812,
        hotspot_enabled: params[16] || false,
        pppoe_enabled: params[17] || false,
        pppoe_interface: params[18] || "",
        pppoe_service_name: params[19] || "",
        mgmt_port: params[20] || 8728,
        notes: params[21] || "",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };
      store.routers.push(router);
      return { rows: [router] };
    }

    // UPDATE routers
    if (lowerText.includes("update routers") && lowerText.includes("set")) {
      // Find router by id (params vary based on what's being updated)
      const idIdx = params.findIndex(
        (p) =>
          (typeof p === "string" && p.startsWith("router-")) ||
          (typeof p === "string" && p.length > 20),
      );
      // Simpler: pass id as last param for SET WHERE id = $N
      // Actually let's handle this differently - the route will construct the query
      // For now, handle the pattern from the routes file
      return { rows: [] };
    }

    // UPDATE routers (specific patterns)
    if (lowerText.includes("update routers")) {
      if (
        lowerText.includes("provision_token") &&
        lowerText.includes("where id")
      ) {
        const router = store.routers.find((r) => r.id === params[0]);
        if (router) {
          router.provision_token = params[1];
          router.updated_at = new Date().toISOString();
          return { rows: [router] };
        }
      }
      if (
        lowerText.includes("provision_status") &&
        lowerText.includes("where id")
      ) {
        const router = store.routers.find((r) => r.id === params[0]);
        if (router) {
          router.provision_status = params[1];
          router.last_provisioned_at = new Date().toISOString();
          router.provision_attempts = (router.provision_attempts || 0) + 1;
          router.updated_at = new Date().toISOString();
          return { rows: [router] };
        }
      }
      // Generic update
      if (lowerText.includes("where id =")) {
        const idParam = params[params.length - 1];
        const router = store.routers.find((r) => r.id === idParam);
        if (router) {
          const fields = [
            "name",
            "identity",
            "model",
            "mac_address",
            "ip_address",
            "wan_interface",
            "lan_interface",
            "dns_servers",
            "ntp_servers",
            "radius_server",
            "radius_secret",
            "radius_port",
            "hotspot_enabled",
            "pppoe_enabled",
            "pppoe_interface",
            "pppoe_service_name",
            "mgmt_port",
            "notes",
          ];
          fields.forEach((field, idx) => {
            if (params[idx] !== undefined && params[idx] !== null) {
              router[field] = params[idx];
            }
          });
          router.updated_at = new Date().toISOString();
          return { rows: [router] };
        }
      }
      return { rows: [] };
    }

    // DELETE routers
    if (lowerText.includes("delete from routers")) {
      const idx = store.routers.findIndex((r) => r.id === params[0]);
      if (idx === -1) return { rows: [] };
      return { rows: store.routers.splice(idx, 1) };
    }

    // UPDATE routers - specific patterns first
    if (
      lowerText.includes("update routers") &&
      lowerText.includes("provision_status")
    ) {
      const idParam = params[params.length - 1];
      console.log(
        "[STORE] provision_status update, idParam:",
        idParam,
        "all params:",
        JSON.stringify(params),
      );
      const router = store.routers.find((r) => r.id === idParam);
      console.log("[STORE] Found router:", !!router);
      if (!router) return { rows: [] };
      router.provision_status = params[0];
      router.last_provisioned_at = new Date().toISOString();
      router.provision_attempts = (router.provision_attempts || 0) + 1;
      router.updated_at = new Date().toISOString();
      console.log("[STORE] Updated router status to:", router.provision_status);
      return { rows: [router] };
    }

    // UPDATE routers - token regen
    if (
      lowerText.includes("update routers") &&
      lowerText.includes("provision_token")
    ) {
      const idParam = params[params.length - 1];
      const router = store.routers.find((r) => r.id === idParam);
      if (!router) return { rows: [] };
      router.provision_token = params[0];
      router.provision_status = "pending";
      router.updated_at = new Date().toISOString();
      return { rows: [router] };
    }

    // UPDATE routers - generic SET with WHERE id
    if (lowerText.includes("update routers")) {
      const idParam = params[params.length - 1];
      const router = store.routers.find((r) => r.id === idParam);
      if (!router) return { rows: [] };

      // Map the SET fields from the devices route
      const fieldNames = [
        "name",
        "identity",
        "model",
        "mac_address",
        "ip_address",
        "wan_interface",
        "lan_interface",
        "dns_servers",
        "ntp_servers",
        "radius_server",
        "radius_secret",
        "radius_port",
        "hotspot_enabled",
        "pppoe_enabled",
        "pppoe_interface",
        "pppoe_service_name",
        "mgmt_port",
        "notes",
      ];

      fieldNames.forEach((field, idx) => {
        if (params[idx] !== undefined && params[idx] !== null) {
          router[field] = params[idx];
        }
      });
      router.updated_at = new Date().toISOString();
      return { rows: [router] };
    }

    // SELECT provision_logs
    if (
      lowerText.includes("select") &&
      lowerText.includes("from provision_logs")
    ) {
      if (lowerText.includes("where router_id")) {
        const logs = store.provision_logs.filter(
          (l) => l.router_id === params[0],
        );
        return {
          rows: logs.sort(
            (a, b) => new Date(b.created_at) - new Date(a.created_at),
          ),
        };
      }
      if (lowerText.includes("where token")) {
        const logs = store.provision_logs.filter((l) => l.token === params[0]);
        return {
          rows: logs.sort(
            (a, b) => new Date(b.created_at) - new Date(a.created_at),
          ),
        };
      }
      return { rows: store.provision_logs };
    }

    // INSERT provision_logs
    if (lowerText.includes("insert into provision_logs")) {
      const log = {
        id: params[0],
        token: params[1],
        router_id: params[2] || null,
        ip_address: params[3] || "unknown",
        user_agent: params[4] || "unknown",
        action: params[5],
        status: params[6],
        details: params[7] || "",
        created_at: new Date().toISOString(),
      };
      store.provision_logs.push(log);
      return { rows: [log] };
    }

    // SELECT provision_events
    if (
      lowerText.includes("select") &&
      lowerText.includes("from provision_events")
    ) {
      if (lowerText.includes("where router_id")) {
        const events = store.provision_events.filter(
          (e) => e.router_id === params[0],
        );
        return {
          rows: events.sort(
            (a, b) => new Date(b.created_at) - new Date(a.created_at),
          ),
        };
      }
      return { rows: store.provision_events };
    }

    // INSERT provision_events
    if (lowerText.includes("insert into provision_events")) {
      const event = {
        id: params[0],
        router_id: params[1],
        event_type: params[2],
        script_content: params[3] || "",
        created_at: new Date().toISOString(),
      };
      store.provision_events.push(event);
      return { rows: [event] };
    }

    return { rows: [] };
  },
};
