[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:server]
command=node /app/server/src/index.js
autostart=true
autorestart=true
stderr_logfile=/var/log/server.err.log
stdout_logfile=/var/log/server.out.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
