/**
 * Main Script Generator Orchestrator
 * Combines all module generators into a complete script
 */

const InterfacesGenerator = require('./interfaces');
const IPConfigGenerator = require('./ipconfig');
const RoutingGenerator = require('./routing');
const FirewallGenerator = require('./firewall');
const ISPServicesGenerator = require('./isp');
const BandwidthGenerator = require('./bandwidth');
const VPNTunnelsGenerator = require('./vpn');
const LoadBalancingGenerator = require('./loadbalancing');
const WirelessGenerator = require('./wireless');
const SystemGenerator = require('./system');

class ScriptGenerator {
  constructor(projectData, version = 'v7') {
    this.projectData = projectData;
    this.version = version;
  }

  generate(moduleConfigs) {
    const scripts = [];

    // Header
    scripts.push('#############################################');
    scripts.push(`# MikroTik RouterOS Configuration Script`);
    scripts.push(`# Generated by MikroTik Config Builder`);
    scripts.push(`# RouterOS Version: ${this.version}`);
    scripts.push(`# Generated: ${new Date().toISOString()}`);
    scripts.push('#############################################');
    scripts.push('');

    // Generate each module
    if (moduleConfigs.interfaces && Object.keys(moduleConfigs.interfaces).length > 0) {
      const gen = new InterfacesGenerator(moduleConfigs.interfaces, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.ipconfig && Object.keys(moduleConfigs.ipconfig).length > 0) {
      const gen = new IPConfigGenerator(moduleConfigs.ipconfig, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.routing && Object.keys(moduleConfigs.routing).length > 0) {
      const gen = new RoutingGenerator(moduleConfigs.routing, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.firewall && Object.keys(moduleConfigs.firewall).length > 0) {
      const gen = new FirewallGenerator(moduleConfigs.firewall, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.isp && Object.keys(moduleConfigs.isp).length > 0) {
      const gen = new ISPServicesGenerator(moduleConfigs.isp, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.bandwidth && Object.keys(moduleConfigs.bandwidth).length > 0) {
      const gen = new BandwidthGenerator(moduleConfigs.bandwidth, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.vpn && Object.keys(moduleConfigs.vpn).length > 0) {
      const gen = new VPNTunnelsGenerator(moduleConfigs.vpn, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.loadbalancing && Object.keys(moduleConfigs.loadbalancing).length > 0) {
      const gen = new LoadBalancingGenerator(moduleConfigs.loadbalancing, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.wireless && Object.keys(moduleConfigs.wireless).length > 0) {
      const gen = new WirelessGenerator(moduleConfigs.wireless, this.version);
      scripts.push(gen.generate());
    }

    if (moduleConfigs.system && Object.keys(moduleConfigs.system).length > 0) {
      const gen = new SystemGenerator(moduleConfigs.system, this.version);
      scripts.push(gen.generate());
    }

    // Footer
    scripts.push('#############################################');
    scripts.push('# End of Configuration Script');
    scripts.push('#############################################');

    return scripts.join('\n');
  }

  // Validate module configuration
  static validateModule(moduleType, config) {
    const errors = [];

    switch (moduleType) {
      case 'interfaces':
        if (config.vlans) {
          config.vlans.forEach((vlan, idx) => {
            if (!vlan.name) errors.push(`VLAN ${idx}: name is required`);
            if (!vlan['vlan-id']) errors.push(`VLAN ${idx}: vlan-id is required`);
            if (!vlan.interface) errors.push(`VLAN ${idx}: interface is required`);
          });
        }
        break;

      case 'ipconfig':
        if (config.addresses) {
          config.addresses.forEach((addr, idx) => {
            if (!addr.address) errors.push(`Address ${idx}: address is required`);
            if (!addr.interface) errors.push(`Address ${idx}: interface is required`);
          });
        }
        break;

      case 'firewall':
        if (config.filter_rules) {
          config.filter_rules.forEach((rule, idx) => {
            if (!rule.chain) errors.push(`Filter rule ${idx}: chain is required`);
            if (!rule.action) errors.push(`Filter rule ${idx}: action is required`);
          });
        }
        break;

      default:
        break;
    }

    return errors;
  }
}

module.exports = ScriptGenerator;
